#!/bin/sh

if dpkg-maintscript-helper supports rm_conffile 2>/dev/null; then
    dpkg-maintscript-helper rm_conffile /etc/wb-rules/load_alarms.js 1.6.7 -- "$@"
    dpkg-maintscript-helper rm_conffile /etc/init.d/wb-rules 2.7.0~ -- "$@"
fi
